# action.yml
name: 'Hello World-geovanamsteste'
description: 'Greet someone and record the time'
inputs:
  owner:  # id of input
    description: 'YOUR_GITHUB_USERNAME'
    required: true
  repos:
    description: 'YOUR_REPOS_NAME'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repos }}
