# action.yml
name: 'Hello World-geovanamsteste'
description: 'Greet someone and record the time'
inputs:
  owner:  # id of input
    description: 'your github username'
    required: true
  repos:
    description: 'your repos name'
    required: true
  access-token: 
    description: 'your user token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repos }}
    - ${{ inputs.access-token }}
    
